# Navigation Links
main:
  - name: About
    url: '#about'
    weight: 10
  - name: Research
    url: '#selected-research'
    weight: 20
  - name: Ongoing
    url: '#ongoing-work'
    weight: 25
  - name: Publications
    url: '#publications'
    weight: 30
  - name: Patents
    url: '#patents'
    weight: 35
  - name: Conferences
    url: '#conferences'
    weight: 37
  - name: Contact
    url: '#contact'
    weight: 40
  - name: CV
    url: uploads/resume.pdf
    weight: 50
